-- SQL about a mechanic shop

CREATE TABLE IF NOT EXISTS users (id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
username VARCHAR(30) NOT NULL, 
password VARCHAR(255) NOT NULL, 
email VARCHAR(50), 
role int(1) NOT NULL DEFAULT '0', 
reg_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mechanic (id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(30) NOT NULL,
password VARCHAR(255) NOT NULL,
email VARCHAR(50),
role int(1) NOT NULL DEFAULT '0',
reg_date TIMESTAMP
);

